### ISSUE TITLE
Disbled languages config option

### ISSUE THREAD

**Issue by KorigamiK** [nvim-treesitter/nvim-treesitter-context#404] opened 2024-02-19 22:52 UTC
Add a new option to disable treesitter-context for certain languages:

```lua
opts = {
    ...
    disable = { "latex" },
}
```
Would be a good option if I want to disable seeing the context in latex files

**Comment by lewis6991** [comment] 2024-02-20 01:06
Duplicate of #172

**Closed by lewis6991** 2024-02-20 01:06 UTC
